fantom/urls.py
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('posts.urls')),
    path('users_app/',include('users_app.urls'))
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path
from .views import *
# from .apps import PostsConfig

# app_name = PostsConfig.name

urlpatterns = [
    path('',index.as_view(),name="index"),
    path('detail/<int:pk>/<slug:slug>',postdetail.as_view(),name='detail'),
    path('post-update/<int:pk>/<slug:slug>',UpdatePostView.as_view(),name='post-update'),
    path('post-delete/<int:pk>/<slug:slug>',DeletePostView.as_view(),name='post-delete'),
    path('category/<int:pk>/<slug:slug>',categorydetail.as_view(),name='category_detail'),
    path('tag/<slug:slug>',TagDetail.as_view(),name='tag_detail'),
    path('post_create/',CreatePostView.as_view(),name='create_post'),
    path('search/',SearchView.as_view(),name='search'),



] 

users_app/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as authViews
app_name = 'users_app'

urlpatterns = [
    path('register/',RegisterView.as_view(),name="register"),
    path('',UserListView.as_view(),name="user_list"),
    path('login/',UserLoginView.as_view(),name='login'),
    path('logout/',UserLogoutView.as_view(),name='logout'),
    path('myprofile/',UserProfileView.as_view(),name='my-profile'),
    path('<int:pk>/',UserPostView.as_view(),name='user_posts'),
    path('update-profile/<slug:slug>/',UserProfileUpdateView.as_view(),name='update_profile'),
    path('password_change/',authViews.PasswordChangeView.as_view(),name='password_change'),
    path('password_change_done/',authViews.PasswordChangeDoneView.as_view(),name="password_change_done"),

] 

templates/base.html
{% load static %}
{% load custom_tags %}
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="icon" href="{% static 'img/favicon.png' %}" type="image/png">
        <title>Fantom Blog</title>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/linericon/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/owl-carousel/owl.carousel.min.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/lightbox/simpleLightbox.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/nice-select/css/nice-select.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/animate-css/animate.css' %}">
        <link rel="stylesheet" href="{% static 'vendors/jquery-ui/jquery-ui.css' %}">
        <!-- main css -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
    </head>
    <body>
        
        <!--================Header Menu Area =================-->
        <header class="header_area">
            {% include 'messages.html' %}
            <div class="logo_part">
            	<div class="container">
            		<a class="logo" href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
            	</div>
            </div>
			<div class="main_menu">
				<nav class="navbar navbar-expand-lg navbar-light">
					<div class="container">
						<!-- Brand and toggle get grouped for better mobile display -->
						<a class="navbar-brand logo_h" href="{% url 'index' %}"><img src="{% static 'img/logo.png' %}" alt=""></a>
						<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
							<span class="icon-bar"></span>
						</button>
						<!-- Collect the nav links, forms, and other content for toggling -->
						<div class="collapse navbar-collapse offset" id="navbarSupportedContent">
							<ul class="nav navbar-nav menu_nav">
								<li class="nav-item active"><a class="nav-link" href="{% url 'index' %}">Home</a></li> 
								<li class="nav-item"><a class="nav-link" href="category.html" >Category</a></li>
								<li class="nav-item"><a class="nav-link" href="{% url 'users_app:user_list' %}">Users</a></li>
                                <li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Category</a>
									<ul class="dropdown-menu">
                                        {% categories as categories %}
                                        {% for category in categories %}
										<li class="nav-item"><a class="nav-link" href="{% url 'category_detail' pk=category.id slug=category.slug %}">{{ category.title }}</a></li>
                                        {% endfor %}
									</ul>
								</li> 
                                {% if user.is_authenticated %}
								<li class="nav-item submenu dropdown">
									<a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">{{ user.username }}</a>
									<ul class="dropdown-menu">
										<li class="nav-item"><a class="nav-link" href="{% url 'create_post' %}">Add post</a></li>
										<li class="nav-item"><a class="nav-link" href="{% url 'users_app:password_change' %}">Change password</a></li>
                                        <li class="nav-item"><a href="{% url 'users_app:my-profile' %}" class="nav-link">My profile</a></li>
                                        <li class="nav-item"><a href="{% url 'users_app:logout' %}" class="nav-link">Logout</a></li>
									</ul>
								</li> 
                                {% else %}
                                <li class="nav-item"><a href="{% url 'users_app:register' %}" class="nav-link">Register</a></li>
                                <li class="nav-item"><a href="{% url 'users_app:login' %}" class="nav-link">Login</a></li>
                                {% endif %}
								<li class="nav-item"><a class="nav-link" href="contact.html">Contact</a></li>
							</ul>
							<ul class="nav navbar-nav navbar-right ml-auto">
								<li class="nav-item"><a href="#" class="search"><i class="lnr lnr-magnifier"></i></a></li>
							</ul>
						</div> 
					</div>
				</nav>
			</div>
        </header>

        {% block content %}

        {% endblock %}


        <footer class="footer-area">
            <div class="container">
                <div class="row">
                    <div class="col-lg-3  col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">About Us</h6>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore dolore magna aliqua.</p>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 col-sm-6">
                        <div class="single-footer-widget">
                            <h6 class="footer_title">Newsletter</h6>
                            <p>Stay updated with our latest trends</p>		
                            <div id="mc_embed_signup">
                                <form target="_blank" action="https://spondonit.us12.list-manage.com/subscribe/post?u=1462626880ade1ac87bd9c93a&amp;id=92a4423d01" method="get" class="subscribe_form relative">
                                    <div class="input-group d-flex flex-row">
                                        <input name="EMAIL" placeholder="Email Address" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Email Address '" required="" type="email">
                                        <button class="btn sub-btn"><span class="lnr lnr-arrow-right"></span></button>		
                                    </div>									
                                    <div class="mt-10 info"></div>
                                </form>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-3 col-md-6 col-sm-6">
                        <div class="single-footer-widget instafeed">
                            <h6 class="footer_title">Instagram Feed</h6>
                            <ul class="list instafeed d-flex flex-wrap">
                                <li><img src="img/instagram/Image-01.jpg" alt=""></li>
                                <li><img src="img/instagram/Image-02.jpg" alt=""></li>
                                <li><img src="img/instagram/Image-03.jpg" alt=""></li>
                                <li><img src="img/instagram/Image-04.jpg" alt=""></li>
                                <li><img src="img/instagram/Image-05.jpg" alt=""></li>
                                <li><img src="img/instagram/Image-06.jpg" alt=""></li>
                                <li><img src="img/instagram/Image-07.jpg" alt=""></li>
                                <li><img src="img/instagram/Image-08.jpg" alt=""></li>
                            </ul>
                        </div>
                    </div>	
                    <div class="col-lg-2 col-md-6 col-sm-6">
                        <div class="single-footer-widget f_social_wd">
                            <h6 class="footer_title">Follow Us</h6>
                            <p>Let us be social</p>
                            <div class="f_social">
                            	<a href="#"><i class="fa fa-facebook"></i></a>
								<a href="#"><i class="fa fa-twitter"></i></a>
								<a href="#"><i class="fa fa-dribbble"></i></a>
								<a href="#"><i class="fa fa-behance"></i></a>
                            </div>
                        </div>
                    </div>						
                </div>
                <div class="row footer-bottom d-flex justify-content-between align-items-center">
                    <p class="col-lg-12 footer-text text-center"><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
                </div>
            </div>
        </footer>
		<!--================ End footer Area  =================-->
        
        
        
        
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/popper.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <script src="{% static 'js/stellar.js' %}"></script>
        <script src="{% static 'vendors/lightbox/simpleLightbox.min.js' %}"></script>
        <script src="{% static 'vendors/nice-select/js/jquery.nice-select.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/imagesloaded.pkgd.min.js' %}"></script>
        <script src="{% static 'vendors/isotope/isotope-min.js' %}"></script>
        <script src="{% static 'vendors/owl-carousel/owl.carousel.min.js' %}"></script>
        <script src="{% static 'vendors/jquery-ui/jquery-ui.js' %}"></script>
        <script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
        <script src="{% static 'js/mail-script.js' %}"></script>
        <script src="{% static 'js/theme.js' %}"></script>
    </body>
</html>

templates/category_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!--================Header Menu Area =================-->
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Category</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
							<a href="#">{{category.title}}</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog_left_sidebar">
							{% for post in posts %}
                            <article class="blog_style1">
                            	<div class="blog_img">
                            		<img class="img-fluid" src="{{ post.image.url }}" alt="" style="width: 100%;"> 
                            	</div>
                            	<div class="blog_text">
									<div class="blog_text_inner">
										{% for tag in post.tag.all %}
										<a class="cat" href="{% url 'tag_detail' tag.slug %}">{{ tag.title }}</a>
										{% endfor %}
										<a href="{% url 'detail' pk=post.id slug=post.slug %}"><h4>{{ post.title }}</h4></a>
										<p>{{ post.content | truncatechars:150 }}</p>
										<div class="date">
											<a href="#"><i class="fa fa-calendar" aria-hidden="true"></i> {{ post.publishing_date }}</a>
											<a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> 05</a>
										</div>	
									</div>
                            	</div>
                            </article>
							{% endfor %}
                            
                           
							{% if is_paginated %}
                            <nav class="blog-pagination justify-content-center d-flex">
							{% if page_obj.has_previous %}
		                        <ul class="pagination">
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
									{% for i in paginator.page_range %}
									{% if page_obj.number == i %}
		                            <li class="page-item active"><a href="#" class="page-link">{{ i }}</a></li>
									{% else %}
		                            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
									{% endif %}
									{% endfor %}
									{% if page_obj.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
		                        </ul>
		                    </nav>
							{% endif %}
                        </div>
                    </div>
                    {% include 'right_side.html' %}
                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
        
       {% endblock %}

templates/create_post.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!--================Header Menu Area =================-->
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>Add post</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <h2 style="text-align: center;color:blue">Create post</h2>
                        <div class="blog_left_sidebar">
							<form method="post" enctype="multipart/form-data">
                                {% csrf_token %}
                                {% if form.errors %}
                                <div id="errors">
                                    <div class="inner">
                                        <p style="color: red;">Please correct the errors below</p>
                                        <ul>
                                            {% for field in form %}
                                            {% if field.errors %}
                                            <li>{{ form.label }} : {{ field.errors | striptags }}</li>
                                            {% endif %}
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>
                                {% endif %}
                                <!-- <div class="mt-10">
                                    <input type="text" name="title" placeholder="Tag" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Tag'" required class="single-input">
                                </div> -->
                                {% for field in form %}
                                <div class="mt-10">
                                    {{ field }}
                                </div>
                                {% endfor %}
                                <div class="mt-10">
                                    <input type="text" name="tag" placeholder="Tag" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Tag'" required class="single-input">
                                </div>
                              
                               
                                <input type="submit" class="genric-btn success circle text-center" style="float: right;margin-top: 30px;" value="Add Post">
                            </form>
                           
                        </div>
                        
                    </div>
                    {% include 'right_side.html' %}
                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
        
       {% endblock %}

templates/messages.html
{% if messages %}

    {% for message in messages %}
    <div class="alert alert-success alert-dismissible">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
    {{ message }}

    </div>
    {% endfor %}

{% endif %}

templates/my-profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!--================Header Menu Area =================-->
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>MY Profile</h2>
						<div class="page_link">
							<img src="{{ userprofile.image.url }}" alt="">
                            <h4 style="color: white;">Username : {{ userprofile.user.username|title }}</h4>
                            <h4 style="color: white;">Birthday : {{ userprofile.birth_day }}</h4>
                            <h4 style="color: white;">Bio : {{ userprofile.bio|linebreaks }}</h4>
                            <a href="{% url 'users_app:update_profile' slug=userprofile.slug %}" class="btn btn-info circle mb-3">update</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog_left_sidebar">
							{% for post in userposts %}
                            <article class="blog_style1">
                            	<div class="blog_img">
                            		<img class="img-fluid" src="{{ post.image.url }}" alt="">
                            	</div>
                            	<div class="blog_text">
									<div class="blog_text_inner">
										{% for tag in post.tag.all %}
										<a class="cat" href="{% url 'tag_detail' tag.slug %}">{{ tag.title }}</a>
										{% endfor %}
										<a href="{% url 'detail' pk=post.id slug=post.slug %}"><h4>{{ post.title }}</h4></a>
										<p>{{ post.content | truncatechars:150 }}</p>
										<div class="date">
											<a href="#"><i class="fa fa-calendar" aria-hidden="true"></i> {{ post.publishing_date }}</a>
											<a href="#"><i class="fa fa-comments-o" aria-hidden="true"></i> 05</a>
										</div>	
									</div>
                            	</div>
                            </article>
							{% endfor %}
                            
                           
							{% if is_paginated %}
                            <nav class="blog-pagination justify-content-center d-flex">
							{% if page_obj.has_previous %}
		                        <ul class="pagination">
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
									{% for i in paginator.page_range %}
									{% if page_obj.number == i %}
		                            <li class="page-item active"><a href="#" class="page-link">{{ i }}</a></li>
									{% else %}
		                            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
									{% endif %}
									{% endfor %}
									{% if page_obj.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
		                        </ul>
		                    </nav>
							{% endif %}
                        </div>
                    </div>
                    {% include 'right_side.html' %}
                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
        
       {% endblock %}

templates/user-list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
        <!--================Header Menu Area =================-->
        
        <!--================Home Banner Area =================-->
        <section class="banner_area">
            <div class="banner_inner d-flex align-items-center">
            	<div class="overlay bg-parallax" data-stellar-ratio="0.9" data-stellar-vertical-offset="0" data-background=""></div>
				<div class="container">
					<div class="banner_content text-center">
						<h2>User's List</h2>
						<div class="page_link">
							<a href="{% url 'index' %}">Home</a>
							<a href="#">{{category.title}}</a>
						</div>
					</div>
				</div>
            </div>
        </section>
        <!--================End Home Banner Area =================-->
        
        <!--================Blog Area =================-->
        <section class="blog_area p_120">
            <div class="container" style="background-color: #F0F0F0;">
                <div class="row">
                    <div class="col-lg-8">
                        <div class="blog_left_sidebar" style="text-align: center;">
							{% for profile in profiles %}
                            <div class="container">
                                <img src="{{ profile.image.url }}" alt="user_img" class="mb-5 circle" style="border: 2px solid green;">
                                <a href="{% url 'users_app:user_posts' pk=profile.user.pk %}"><h4 style="color: darkblue;">{{ profile.user.username }}</h4></a>
                                <p style="color: black;font-style:italic">{{ profile.bio}}</p>
                                <p>{{ profile.birth_day}}</p>
                            </div>
                            
							{% endfor %}
                            
                           
							{% if is_paginated %}
                            <nav class="blog-pagination justify-content-center d-flex">
							{% if page_obj.has_previous %}
		                        <ul class="pagination">
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.previous_page_number }}" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Previous">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-left"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
									{% for i in paginator.page_range %}
									{% if page_obj.number == i %}
		                            <li class="page-item active"><a href="#" class="page-link">{{ i }}</a></li>
									{% else %}
		                            <li class="page-item"><a href="?page={{ i }}" class="page-link">{{ i }}</a></li>
									{% endif %}
									{% endfor %}
									{% if page_obj.has_next %}
		                            <li class="page-item">
		                                <a href="?page={{ page_obj.next_page_number }}" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% else %}
									<li class="page-item disabled">
		                                <a href="#" class="page-link" aria-label="Next">
		                                    <span aria-hidden="true">
		                                        <span class="lnr lnr-chevron-right"></span>
		                                    </span>
		                                </a>
		                            </li>
									{% endif %}
		                        </ul>
		                    </nav>
							{% endif %}
                        </div>
                    </div>
                    {% include 'right_side.html' %}
                </div>
            </div>
        </section>
        <!--================Blog Area =================-->
        
       {% endblock %}